# Generated by Django 4.2.11 on 2024-03-25 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("subject", models.CharField(max_length=100)),
                ("complaint", models.TextField(max_length=100)),
                ("seen", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Fees",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_date", models.DateField()),
                ("to_date", models.DateField()),
                ("room_rent", models.FloatField(default=0)),
                ("mess_bill", models.FloatField(default=0)),
                ("amount", models.FloatField(default=0)),
                ("status", models.BooleanField(default=False)),
                ("paid_by", models.CharField(max_length=100)),
                ("paid_date", models.DateField(null=True)),
                ("payment", models.CharField(max_length=100)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("breakfast", models.CharField(max_length=100)),
                ("lunch", models.CharField(max_length=100)),
                ("dinner", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="HostelDetails",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_rooms", models.CharField(max_length=100)),
                ("occupied", models.CharField(max_length=100)),
                ("annual_expenses", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("contact_no", models.CharField(max_length=10)),
                ("room_facilities", models.TextField(max_length=200)),
                ("image1", models.ImageField(upload_to="")),
                ("image2", models.ImageField(upload_to="")),
                ("image3", models.ImageField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("received", models.CharField(max_length=100)),
                ("given", models.CharField(max_length=100)),
                ("total_income", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("to", models.CharField(max_length=100)),
                ("notification", models.TextField(max_length=100)),
                ("time", models.TimeField()),
                ("timestamp", models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("review", models.TextField(max_length=200)),
                ("seen", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="StaffRegister",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("mobile", models.CharField(max_length=10)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment", models.CharField(max_length=100)),
                ("card_no", models.CharField(max_length=30)),
                ("card_cvv", models.CharField(max_length=30)),
                ("expiry_month", models.CharField(max_length=20)),
                ("expiry_year", models.CharField(max_length=20)),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_payment",
                        to="adminmodule.fees",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Egrant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course", models.CharField(max_length=50)),
                ("academic_year", models.CharField(max_length=50)),
                ("cast", models.CharField(max_length=50)),
                ("yearly_income", models.CharField(max_length=100)),
                ("approval_status", models.BooleanField(default=0)),
                ("seen", models.BooleanField(default=False)),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookRoom",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_joining", models.DateField()),
                ("booking_date", models.DateField(auto_now_add=True)),
                ("status", models.IntegerField(default=0)),
                ("seen", models.BooleanField(default=False)),
                (
                    "booked_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("attendance", models.CharField(max_length=100)),
                ("time", models.TimeField()),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance",
                        to="accounts.student",
                    ),
                ),
            ],
        ),
    ]
