# Generated by Django 3.1.3 on 2021-05-23 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210523_1116'),
        ('adminmodule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookroom',
            name='name',
        ),
        migrations.AddField(
            model_name='bookroom',
            name='student',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='accounts.student'),
            preserve_default=False,
        ),
    ]
