# Generated by Django 3.1.3 on 2020-11-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_rooms', models.CharField(max_length=100)),
                ('occupied', models.CharField(max_length=100)),
                ('annual_expenses', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=100)),
            ],
        ),
    ]
