# Generated by Django 3.1.3 on 2020-12-08 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffregister',
            name='password',
        ),
        migrations.RemoveField(
            model_name='staffregister',
            name='username',
        ),
    ]
