# Generated by Django 3.1.3 on 2021-05-23 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminmodule', '0002_auto_20210523_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookroom',
            name='booked_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
            preserve_default=False,
        ),
    ]
