# Generated by Django 3.1.3 on 2020-12-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0003_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received', models.CharField(max_length=100)),
                ('given', models.CharField(max_length=100)),
                ('total_income', models.CharField(max_length=100)),
            ],
        ),
    ]
