# Generated by Django 3.1.3 on 2021-05-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0003_bookroom_booked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='timestamp',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
