# Generated by Django 3.1.3 on 2021-05-23 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0004_notification_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='e_grant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminmodule.egrant'),
        ),
    ]
