# Generated by Django 3.1.3 on 2021-05-23 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0005_auto_20210523_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paid_by',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='student_name',
        ),
        migrations.AddField(
            model_name='fees',
            name='paid_by',
            field=models.CharField(default='aa', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fees',
            name='payment',
            field=models.CharField(default=1000, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='bill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fee_payment', to='adminmodule.fees'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='card_cvv',
            field=models.CharField(default=222, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='card_no',
            field=models.CharField(default=7654653627635467, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='expiry_month',
            field=models.CharField(default='May', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='expiry_year',
            field=models.CharField(default=2023, max_length=20),
            preserve_default=False,
        ),
    ]
