# Generated by Django 3.1.3 on 2021-05-23 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0006_auto_20210523_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fees',
            name='e_grant',
        ),
    ]
