# Generated by Django 3.1.3 on 2020-12-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0006_notification_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('initial_day', models.DateField()),
                ('final_day', models.DateField()),
                ('percentage', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification',
            field=models.TextField(max_length=100),
        ),
    ]
