# Generated by Django 3.1.3 on 2021-05-23 12:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0007_remove_fees_e_grant'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees',
            name='paid_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 23, 12, 42, 4, 185779, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
